### ISSUE TITLE
Set zookeeper hosts is only run once, resulting in wrong ip when zk_inventory_group is dynamic

### ISSUE THREAD

**Issue by jsommr** [lean-delivery/ansible-role-solr-cloud#6]
If managing multiple independent SolrCloud's, where `zk_inventory_group` is set to a dynamic variable like `"zookeeper_location_{{ location }}"`, then it results in all Solr nodes getting the ip of the first inventory group. All inventory groups should be taken into account.

In tasks/Linux.yml `run_once` is set to True:
```
- name: Set zookeeper hosts
  set_fact:
    zk_hosts: '{{ zk_hosts }} + [ "{{ host }}:{{ zk_client_port }}" ]'
  loop: '{{ zk_hosts_list }}'
  loop_control:
    loop_var: host
  run_once: True
```

run_once should be removed to ensure all Solr nodes point to the right Zookeepers
